name: Upgrade
on:
  workflow_dispatch:
jobs:
  Promote:
    name: Upgrade
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Merge
        run: |
          git config --global user.name 'Jonathan Brink'
          git config --global user.email 'jonbri@users.noreply.github.com'
          yarn songandverse
          git push origin main

